name: 'release'

on:
  push:
    tags: [ '*' ]

jobs:
  release-darwin-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: amd64
          goarch: darwin
#          RELEASE_NAME: ${{ github.ref }}
