name: 'release'

on:
  push:
    tags: [ '*' ]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build/publish in parallel: linux; 386/amd64/arm64, windows; 386/amd64, darwin; amd64/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "arm64"
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz"
          project_path: "./src/go"
          binary_name: "meetings-by-venue-type"
          extra_files: LICENSE README.md
